apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodeapp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodeapp
    app.kubernetes.io/part-of: test-application
  name: nodeapp
  namespace: hacbs
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: nodeapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: nodeapp
    spec:
      containers:
      - image: quay.io/karthik_jk/nodeapp@sha256:1b7320bb573959602767f2f612a75ad3098d3da8ee760a12b9b95862d6c5035c
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
